include: .gitlab-ci.pymodule.yml

variables:
  PACKAGE_NAME: readcsv

prep:
  extends: .prep

build:
  extends: .build

test-install:
  extends: .test-install

run-examples:
  extends: .run-examples
  script:
    - . venv/bin/activate
    - pip install ${PIP_OPTIONS} dist/*.whl
    - python3 -m readcsv.test_csvreader
    - python3 -m readcsv.examples

docs:
  extends: .docs

pages:
  extends: .pages

upload-successful:
  extends: .upload-successful
