image: python:3.9-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PACKAGE_NAME: readcsv

.cache-paths: &cache-paths
    paths:
      - .cache/pip
      - venv

.cache-user:
  cache:
    <<: *cache-paths
    policy: pull

.cache-creator:
  cache:
    <<: *cache-paths
    policy: push

before_script:
  - /usr/bin/python3 -V  # Print out python version for debugging
  - env| egrep 'CI_|PIP_' || true

stages:
  - prep
  - build
  - install
  - test
  - docs


prep:
  extends: .cache-creator
  stage: prep
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip build wheel setuptools
  tags:
    - container

build:
  extends: .cache-user
  stage: build
  script:
    - . venv/bin/activate
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl
  tags:
    - container

test-install:
  extends: .cache-user
  stage: install
  script:
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list
  tags:
    - container

run-examples:
  extends: .cache-user
  stage: test
  script:
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list
    - python3 -m readcsv.test_csvreader
    - python3 -m readcsv.examples
  tags:
    - container

.docs-stage:
  extends: .cache-user
  stage: docs
  script:
    - . venv/bin/activate
    - pip list
    - pip install pytest pdoc3
    - pip install dist/*.whl
    - pip list
    - mkdir -p public
    - PYTHONPATH=src pdoc $PACKAGE_NAME > public/README_api.md
    - PYTHONPATH=src pdoc --html -o public/html $PACKAGE_NAME
  artifacts:
    paths:
      - public
  tags:
    - container

docs:
  extends: .docs-stage
  except:
    - master
    
pages:
  extends: .docs-stage
  only:
    - master
