image: python:3.9-buster

variables:
  PACKAGE_NAME: readcsv
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

.common:
  tags:
  - container

.cache-paths: &cache-paths
  paths:
    - .cache/pip
    - venv

.cache-user:
  extends: .common
  cache:
    <<: *cache-paths
    policy: pull

.cache-creator:
  extends: .common
  cache:
    <<: *cache-paths
    policy: push

before_script:
  - python3 -V  # Print out python version for debugging
  - env| egrep 'CI_|PIP_' || true

stages:
  - prep
  - build
  - install
  - test
  - docs
  - upload-successful

prep:
  extends: .cache-creator
  stage: prep
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - if test -n "$TWINE_UPLOAD" ; then export PIP_EXTRA_INDEX_URL=$TWINE_REPOSITORY/simple/ ; fi
    - pip install --upgrade pip build wheel setuptools

build:
  extends: .cache-user
  stage: build
  script:
    - . venv/bin/activate
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl

test-install:
  extends: .cache-user
  stage: install
  script:
    - . venv/bin/activate
    - pip list
    - pip install dist/*.whl
    - pip list

run-examples:
  extends: .cache-user
  stage: test
  script:
    - . venv/bin/activate
    - pip install dist/*.whl
    - python3 -m readcsv.test_csvreader
    - python3 -m readcsv.examples

.docs-stage:
  extends: .cache-user
  stage: docs
  script:
    - . venv/bin/activate
    - pip install pytest pdoc3 dist/*.whl
    - mkdir -p public
    - PYTHONPATH=src pdoc $PACKAGE_NAME > public/README_api.md
    - PYTHONPATH=src pdoc --html -o public/html $PACKAGE_NAME
  artifacts:
    paths:
      - public

docs:
  extends: .docs-stage
  except:
    - master
    
pages:
  extends: .docs-stage
  only:
    - master

upload-successful:
  extends: .cache-user
  stage: upload-successful
  script:
    - . venv/bin/activate
    - test -n "${TWINE_UPLOAD}" && pip install twine
    - test -n "${TWINE_UPLOAD}" && twine upload -u "${TWINE_USERNAME}" --repository-url "${TWINE_REPOSITORY}" dist/*.whl
